# kubectl apply -f hct-alquiler-jauregui-maylin-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hct-alquiler-jauregui-maylin-deployment
  namespace: hct-alquiler-jauregui-maylin-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hct-alquiler-jauregui-maylin-deployment        # Debe coincidir con las etiquetas del Service
  template:
    metadata:
      labels:
        app: hct-alquiler-jauregui-maylin-deployment      # Debe coincidir con las etiquetas del Service
    spec:
      containers:
        - name: hct-alquiler-jauregui-maylin-container
          image: userdockerhub/hct-alquiler-latest   # Reemplaza con tu imagen Docker Hub
          imagePullPolicy: IfNotPresent        # Evitar traer siempre la última versión si hay una actual
          envFrom:
            - secretRef:
                name: hct-alquiler-jauregui-maylin-secret # Esto cargará todos los valores como variables de entorno
