# kubectl apply -f hct-vehiculo-jauregui-maylin-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: hct-vehiculo-jauregui-maylin-secret
  namespace: maylin-jauregui-22-namespace
type: Opaque
data:
  PORT: ODA5MA==
  MONGODB_URI: amRiYzpoMjptZW06YWNhZGVteWRi   # en Base64
  GHIBLI_URL: aHR0cHM6Ly9haS1naGlibGktaW1hZ2UtZ2VuZXJhdG9yLnAucmFwaWRhcGkuY29tL3RleHR0b2ltYWdlZ2hpYmxp  # en Base64
  GHIBLI_KEY: ZjZmMjRlY2RlOW1zaGQwMjkyYjE3YTZhYmM1ZnAxMTM0NWZqc242NzgzYjczMmI4Y2Y=  # en Base64
  GHIBLI_HOST: YWktZ2hpYmxpLWltYWdlLWdlbmVyYXRvci5wLnJhcGlkYXBpLmNvbQ==   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode